[tools]
darklua = "seaofvoices/darklua@0.12.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
rojo = "rojo-rbx/rojo@7.4.1"
stylua = "johnnymorganz/stylua@0.20.0"
selene = "kampfkarren/selene@0.26.1"
luau-lsp = "johnnymorganz/luau-lsp@1.27.1"
lune = "lune-org/lune@0.8.5"
rbxcloud = "Sleitnick/rbxcloud@0.13.0"
