[package]
name = "itsjames212/project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Sift = "csqrl/sift@0.0.8"
Loader = "sleitnick/loader@2.0.0"

Bin = "red-blox/bin@^1.0.0"         # https://util.redblox.dev/bin.html
Fetch = "red-blox/fetch@^2.0.0"     # https://util.redblox.dev/fetch.html
Future = "red-blox/future@^1.0.0"   # https://util.redblox.dev/future.html
Guard = "red-blox/guard@^1.0.0"     # https://util.redblox.dev/guard.html   
Promise = "red-blox/promise@^1.0.0" # https://util.redblox.dev/promise.html
Signal = "red-blox/signal@^2.0.0"   # https://util.redblox.dev/signal.html
Spawn = "red-blox/spawn@^1.0.0"     # https://util.redblox.dev/spawn.html
Red = "red-blox/red@2.3.0"          # https://red.redblox.dev/guide/introduction/what-is-red.html

React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
VirtualizedList = "jsdotlua/virtualized-list@1.3.5"

[server-dependencies]
Lapis = "nezuo/lapis@0.2.9"
DataStoreServiceMock = "nezuo/data-store-service-mock@0.3.5"
Mock-Memory-Store-Service = "vorlias/mock-memory-store-service@0.2.0"
