name: Production Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        shell: bash
        env:
          UID: 6143989178 # Game Id
          PID: 18123720650 # Place Id
        run: | # can run lune scripts right after sh scripts/build.sh
          sh scripts/build.sh
          rbxcloud experience publish -f placefile.rbxl -p "$PID" -u "$UID" -t published -a ${{ secrets.API_KEY }}